config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  resources :users
  resources :posts do
    resources :post_details, only: [:new, :create, :destroy]
  end 
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :image, presence: true
  validates :user_id, presence: true
  
  belongs_to :user
  has_many :post_details, :dependent => :destroy
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  
  mount_uploader :image, ImageUploader
end

app/models/post_detail.rb
class PostDetail < ApplicationRecord
  validates :post_id, presence: true
  validates :content, presence: true
  validates :image, presence: true
  
  mount_uploader :image, ImageUploader
  
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 15 } 
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :password, presence: true, format: { with: /\A(?=.*?[a-zA-Z])(?=.*?\d)[a-zA-Z\d]{8,32}+\z/i }, on: :create
  validates :password, presence: true, format: { with: /\A(?=.*?[a-zA-Z])(?=.*?\d)[a-zA-Z\d]{8,32}+\z/i }, on: :update, allow_blank: true
  
  has_secure_password
  
  mount_uploader :image, ImageUploader
  
  has_many :posts, :dependent => :destroy
  has_many :favorites
  has_many :favorites_posts, through: :favorites, source: 'post'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  add_flash_types :success, :info, :warning, :danger
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end  
  #binding.pry
  def logged_in?
    !current_user.nil?
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @user = User.find(params[:id])
    @favorite_posts = @user.favorites_posts
  end
  
  def create
    favorite =Favorite.new
    favorite.user_id = current_user.id
    favorite.post_id = params[:post_id]
    @post = Post.find(params[:post_id])
    favorite.save
  end
  
  def destroy
    favorite = Favorite.find_by(
      user_id: current_user.id,
      post_id: params[:post_id]
      ) 
    @post = Post.find(params[:post_id])
    favorite.destroy
  end  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/post_details_controller.rb
class PostDetailsController < ApplicationController
  
  def new
    @post = Post.find_by(id: params[:post_id])
    if current_user.id == @post.user_id
      @post_detail = PostDetail.new
    else
      redirect_to posts_path, danger: '権限がありません'
    end  
  end
  
  def create
    @post = Post.find_by(id: params[:post_id])
    if current_user.id == @post.user_id
      @post_detail = PostDetail.new(post_detail_params)
      @post_detail.post_id = params[:post_id]
      if @post_detail.save
        redirect_to new_post_post_detail_path(post_id: @post.id)
      else
        render :new
      end
    else
      redirect_to posts_path, danger: '権限がありません'
    end 
  end
  
  def destroy
    @post = Post.find_by(id: params[:post_id])
    if current_user.id == @post.user_id
      @post_detail = PostDetail.find(params[:id])
      @post_detail.destroy
      redirect_to new_post_post_detail_path(post_id: @post.id)
    else
      redirect_to posts_path, danger: '権限がありません'
    end  
  end  
  
  private
  def post_detail_params
    params.require(:post_detail).permit(:image, :content)
  end  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  PER = 8
  
  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result.includes(:favorite_users).page(params[:page]).per(PER)
  end  
  
  def new
    if logged_in?
      @post = Post.new
    else
      redirect_to root_path, danger: 'ログインが必要です'
    end  
  end
  
  def create
    if logged_in?
      @post = current_user.posts.new(post_params)
      if @post.save
        redirect_to posts_path, success: '投稿に成功しました'
      else
        flash.now[:danger] = '投稿に失敗しました'
        render :new
      end  
    else
      redirect_to root_path, danger: 'ログインが必要です'
    end  
  end
  
  def show
    if logged_in?
      @post = Post.find(params[:id])
      #binding.pry
    else
      redirect_to root_path, danger: '投稿詳細を見るためにはログインが必要です'
    end  
  end
  
  def destroy
    @post = Post.find_by(id: params[:id])
    if current_user.id == @post.user_id
      @post.destroy
      flash[:success] = "イラストを削除しました"
      redirect_to posts_path
    else
      redirect_to posts_path, danger: '権限がありません'
    end  
  end  
  
  private
  def post_params
    params.require(:post).permit(:title, :image)
  end
end  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: email_params[:email])
    if user && user.authenticate(password_params[:password])
      log_in user
      redirect_to root_path, success: 'ログインに成功しました'
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end  
  end      
  
  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end  
  
  def log_in(user)
    session[:user_id] = user.id
  end  
  
  private  
  def email_params
    params.require(:session).permit(:email)
  end  
  
  def password_params
    params.require(:session).permit(:password)
  end  
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    #binding.pry
    @user = User.new(user_params)
    @user.image = "人物アイコン.jpeg"
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end  
  
  def show
    @user = User.find(params[:id])
    @posts = Post.all
  end  
  
  def edit
    if current_user.id == params[:id].to_i
      @user = User.find(params[:id])
    else 
      flash[:danger] = "権限がありません"
      redirect_to posts_path
    end    
  end  
  
  def update
    if current_user.id == params[:id].to_i
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to user_path(@user)
        flash[:success] = 'ユーザー情報を編集しました。'
      else
        flash.now[:danger] = 'ユーザー情報の編集に失敗しました。'
        render :edit
      end  
    else 
      flash[:danger] = "権限がありません"
      redirect_to posts_path
    end   
  end  
  
  def destroy
    if current_user.id == params[:id].to_i
      @user = User.find_by(id: params[:id])
      @user.destroy
      flash[:success] = "ユーザーを削除しました"
      redirect_to root_path
    else 
      flash[:danger] = "権限がありません"
      redirect_to posts_path
    end    
  end  
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_details_helper.rb
module PostDetailsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorite.html.erb
<% if logged_in? %>
  <% if post.favorite_users.include?(current_user) %>
    <%= link_to favorites_path(post_id: post.id), method: :delete, remote: true do %>
      <span class="fa fa-heart like-btn-unlike fa-2x"></span>
    <% end %>
    <div class="post-favorite_users-count">
      <%= post.favorite_users.count %>
    </div>  
  <% else %>
    <%= link_to favorites_path(post_id: post.id), method: :post, remote: true do %>
      <span class="fa fa-heart like-btn fa-2x"></span>
    <% end %>
    <div class="post-favorite_users-count">
      <%= post.favorite_users.count %>
    </div>  
  <% end %>
<% end %>
  

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @post.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {post: @post}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @post.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {post: @post}) %>");

app/views/favorites/index.html.erb
<div class="main posts-index">
  <div class="container">
    <% @favorite_posts.each do |post| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="posts-index-item">
              <%= link_to user_path(post.user) do %>
                <div class="post-left">
                  <div class="img">
                  　<% if post.user.image? %>
                　　　　<%= image_tag post.user.image.url %>
                　　<% else %>
                      <%= image_tag asset_path("/assets/人物アイコン.jpeg") %>
            　　　 　 　<% end %>
                  </div> 
                </div>
                <div class="post-right">
                  <h4 class="post-user-name">
                    <%= post.user.name %><br>
                  </h4>
                </div>
              <% end %>
              <%= link_to post_path(post.id) do %>
                <h3 class="post-title">
                  <%= post.title %>
                </h3>
                <%= image_tag post.image.url %>
              <% end %>
              <div id="favorites_buttons_<%= post.id %>">
                <%= render partial: 'favorites/favorite', locals: { post: post} %>
              </div> 
            </div>
        </div>
      </div>
    <% end %>
  </div>
</div>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oekakilog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    <header>
      <div class="header-logo">
        <%= link_to("Oekakilog", root_path) %>
      </div>
      <ul class="header-menus">
        <% if current_user %>
          <li>
            <%= link_to("#{current_user.name}さん", user_path(current_user) ) %>
          </li>
          <li>
            <%= link_to("イラスト投稿", new_post_path) %>
          </li>
          <li>
            <%= link_to("イラスト一覧", posts_path) %>
          </li>
          <li>
            <%= link_to("ログアウト", logout_path, {method: :delete}) %>
          </li>
        <% else %>
          <li>
            <%= link_to("ログイン", sessions_new_path) %>
          </li>
          <li>
            <%= link_to("新規登録", new_user_path) %>
          </li>
        <% end %>  
      </ul>
    </header>
  
    <%= yield %>
    
    <script>
      $(function(){
        $(".alert").fadeOut(5000);
      });
    </script>
  </body>
</html>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">おえかきログはあなたのお絵かきの進め方の記録を共有できるサービスです</h1>
    <div class="row">
      <% if logged_in? %>
        <div class="col-md-offset-3 col-md-3">
          <%= link_to 'イラスト投稿', new_post_path, class: 'btn btn-block btn-white' %>
        </div>
        <div class="col-md-3">
          <%= link_to 'イラスト一覧', posts_path, class: 'btn btn-block btn-white' %>
        </div>
      <% else %>
        <div class="col-md-offset-3 col-md-3">
          <%= link_to '新規登録', new_user_path, class: 'btn btn-block btn-white' %>
        </div>
        <div class="col-md-3">
          <%= link_to 'ログイン', login_path,class: 'btn btn-block btn-white' %>
        </div>
      <% end %>  
    </div>
  </div>
</div>

app/views/post_details/new.html.erb
<div class="main post-show">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="posts-index-item">
          <h3 class="post-title">
            <%= @post.title %>
          </h3>
          <%= image_tag @post.image.url %>
        </div>
        <div class="posts-index-item">
          <h4 class="drawing-process-heading">
            <%= "絵を描く手順を追加" %>
          </h4>
          <% @post.post_details.each_with_index do |post_detail, i| %>
            <h4 class="drawing-process-index">
              <%= "#{i+1}" %>
            </h4>
            <div class="drawing-process-image">
              <%= image_tag post_detail.image.url %>
            </div>
            <div class="drawing-process-explanation">
              <div class="txt">
                <%= post_detail.content %>
              </div>  
            </div>
            <div class="drawing-process-delete">
              <%= link_to "この途中手順を削除", post_post_detail_path(id: post_detail.id), method: :delete, data:
              { confirm: 'この途中手順を削除しますか?' } %>
            </div>
          <% end %>
          
          <%= form_for @post_detail, url: post_post_details_path do |f| %>
            <div class="form-group">
              <%= f.label :途中手順の画像ファイルを選択 %>
              <%= f.file_field :image %>
            </div>
            
            <div class="form-group">
              <%= f.label :手順の説明 %>
              <%= f.text_area :content, class: 'form-control-2' %>
            </div>
            <% @post_detail.errors.full_messages.each do |message| %>
            <div class="form-error">
              <%= message %>
            </div>
            <% end %>
            <%= f.submit '手順を追加', class: 'btn btn-black btn-block' %>
          <% end %>
          <h4 class="drawing-process-path">
              <%= link_to "イラスト詳細ページにもどる", post_path(id: @post.id) %>
          </h4>
        </div>  
      </div>
    </div>
  </div>  
</div>

app/views/posts/index.html.erb
<div class="main posts-index">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="posts-index-item">
          <%= search_form_for @q do |f| %>
            <%= f.label :title, "タイトルから絵を検索" %>
            <%= f.search_field :title_cont %>
            
            <%= f.submit "検索" %>
          <% end %>
        </div>  
        <% @posts.each do |post| %>
          <div class="posts-index-item">
            <%= link_to user_path(post.user) do %>
              <div class="post-left">
                <div class="img">
                　<% if post.user.image? %>
              　　　　<%= image_tag post.user.image.url %>
              　　<% else %>
                    <%= image_tag asset_path("/assets/人物アイコン.jpeg") %>
          　　　 　 　<% end %>
                </div> 
              </div>
              <div class="post-right">
                <h4 class="post-user-name">
                  <%= post.user.name %><br>
                </h4>
              </div>
            <% end %>
            <%= link_to post_path(post.id) do %>
              <h3 class="post-title">
                <%= post.title %>
              </h3>
              <%= image_tag post.image.url %>
            <% end %>
            <div id="favorites_buttons_<%= post.id %>">
              <%= render partial: 'favorites/favorite', locals: { post: post} %>
            </div>
          </div>
        <% end %>
        <%= paginate @posts %>
      </div>
    </div>  
  </div>
</div>

app/views/posts/new.html.erb
<div class="main posts-new">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">イラスト投稿</h1>
        <% @post.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>
        <%= form_for @post do |f| %>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image %>
          </div>
          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
        <% end %> 
      </div>
    </div>
  </div> 
</div>

app/views/posts/show.html.erb
<div class="main post-show">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="posts-index-item">
          <%= link_to user_path(@post.user) do %>
            <div class="post-left">
              <div class="img">
              　<% if @post.user.image? %>
                  <%= image_tag @post.user.image.url %>
            　　<% else %>
                  <%= image_tag asset_path("/assets/人物アイコン.jpeg") %>
                <% end %>
              </div>
            </div>
            <div class="post-right">
              <h4 class="post-user-name">
                <%= @post.user.name %><br>
              </h4>
            </div>
          <% end %>
          <h3 class="post-title">
            <%= @post.title %>
          </h3>
          <%= image_tag @post.image.url %>
          <div id="favorites_buttons_<%= @post.id %>">
            <%= render partial: 'favorites/favorite', locals: { post: @post} %>
          </div>
          <% if @post.user_id == current_user.id %> 
            <div class="post-show-link">
              <%= link_to new_post_post_detail_path(post_id: @post.id) do %>
                <%= "手順を追加" %><br>
              <% end %>
              <%= link_to '投稿を削除', post_path(params[:id]), method: :delete, data:
              { confirm: '本当に投稿を削除しますか?' } %>
            </div>
          <% end %>  
        </div>
        <% if @post.post_details.present?  %>
          <div class="posts-index-item">
            <% @post.post_details.each_with_index do |post_detail, i| %>
              <% if i == 0 %>
                <h4 class="drawing-process-heading-2">
                <%= "描く手順" %>
                </h4>
              <% end %>  
              <h4 class="drawing-process-index">
                <%= "#{i+1}" %>
              </h4>
              <div class="drawing-process-image">
                <%= image_tag post_detail.image.url %>
              </div>
              <div class="drawing-process-explanation">
                <div class="txt">
                  <%= post_detail.content %>
                </div>  
              </div>
            <% end %>
          </div>
        <% end %>  
      </div>
    </div>
  </div>  
</div>

app/views/users/edit.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">ユーザー情報の編集</h1>
          <% @user.errors.full_messages.each do |message| %>
            <div class="form-error">
              <%= message %>
            </div>
          <% end %> 
        <%= form_for @user, url: user_path(current_user) do |f| %>
          <div class="form-group">
            <%= f.label :お名前, class: "text-white" %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :メールアドレス, class: "text-white" %>
            <%= f.text_field :email, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :ユーザー画像, class: "text-white" %>
            <%= f.file_field :image, class: "form-control" %>
          </div>
          <%= f.submit "保存", class: "btn-block btn-white" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">新規登録</h1>
          <% @user.errors.full_messages.each do |message| %>
            <div class="form-error">
              <%= message %>
            </div>
          <% end %>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :お名前, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :メールアドレス, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :パスワード, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :パスワード確認, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          
          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path,class: 'text-white' %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main user-show">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="user">
          <div class="img">
          　<% if @user.image? %>
        　　　　<%= image_tag @user.image.url %>
        　　<% else %>
              <%= image_tag asset_path("/assets/人物アイコン.jpeg") %>
    　　　   　<% end %>
          </div>  
          <h2><%= @user.name %></h2>
          <p><%= @user.email %></p>
          <%= link_to("いいねしたイラスト一覧", favorites_index_path(id: params[:id])) %><br>
          <% if @user.id == current_user.id %>
            <%= link_to("アカウントを編集", edit_user_path(current_user)) %><br>
            <%= link_to 'アカウントを削除', user_path(current_user), method: :delete, data:
            { confirm: '本当にアカウントを削除しますか?' } %>
          <% end %>  
        </div>
        <% @user.posts.each do |post| %>
          <div class="posts-index-item">
            <div class="post-left">
              <div class="img">
              　<% if post.user.image? %>
            　　　　<%= image_tag post.user.image.url %>
            　　<% else %>
            　  　  <%= image_tag "/assets/人物アイコン.jpeg" %>
        　　　 　 　<% end %>
              </div> 
            </div>
            <div class="post-right">
              <h4 class="post-user-name">
                <%= post.user.name %><br>
              </h4>
            </div>
            <%= link_to post_path(post.id) do %>
              <h3 class="post-title">
                <%= post.title %>
              </h3>
              <%= image_tag post.image.url %>
              <div id="favorites_buttons_<%= post.id %>">
                <%= render partial: 'favorites/favorite', locals: { post: post} %>
              </div>
            <% end %>   
          </div>
        <% end %>
      </div>  
    </div>    
  </div>
</div>